### ISSUE TITLE
Feature Enhancement Request: Option to immediately run a cron via the admin portal 

### ISSUE THREAD

**Issue by theaccordance** [innovato/strapi-plugin-cron#3]
Hello team,

I came across your project this week while building a Strapi instance for a side project I'm spinning up, THANK YOU for the hard work you've done so far.  While the framework's cron system isn't difficult to implement, having the UI option for the admin panel is huge in terms of maintaining an application long-term in a collaborative environment.  

In terms of product feedback, one feature enhancement I wanted to start a discussion around was having some type of trigger to immediately run a cron job, such as a button in the UI.  At least in my use case, this would help address two needs:
- As a developer, I can more quickly iterate as I write my cron scripts for my project
- As an Admin, I may want to execute a cron before it's next scheduled run (example: syncing data from third-party sources) 

I realize I could tweak my configuration to solve my problem (which is what I'm doing right now for cron development) but once my project gets into a production setting, I don't want my admins tweaking cron schedules if they want to run an immediate execution.

Lastly - I'm well-versed with the OSS scene, so consider this feedback free of any obligation to commit.  I might try to solve it myself, but I'm trying to stay focused on meeting the GTM requirements for my side project first.  Feel free to tag me if you have any follow up questions.

**Comment by wgnahs** [comment]
Hey [theaccordance](https://github.com/theaccordance)!

Thanks for using our plugin! I agree on that the cron system isn't difficult to implement, but we still missed a good overview on the crons. That's why we've decided to build this plugin.

> I wanted to start a discussion around was having some type of trigger to immediately run a cron job, such as a button in the UI. 

This is on our wish list as well and will be developed soon. Since this is a side-project of ours and have been pretty busy lately, we will find ourselves some time to work on this feature.

We very much appreciate any more feedback! We will also submit this project into the Strapi store soon.

I'll keep you posted!

**Comment by longd3** [comment]
Hi @wgnahs,
Is it going to be implemented soon? Can't wait .. >.>
Appreciate the hard work

**Comment by mjnoach** [comment]
Hi @longd3,

since releasing this project I have lost the original working setup for development. I've attempted setting up this repo for development again (to work on requested issues) by cloning it from its current state, but I never could get it to work so far. There are some tricky ts import errors which I couldn't crack down yet. Also having se it up to the point of being able to start up the dev server, changes made to the plugin src files are not reflected in the running dev app - so that's another blocker atm. I have some spare time this weekend, so I'm going to give it yet another try. If I do, I'll implement the requested features shortly after. I will let you know if I progress past the current obstacles and get those features implemented.

Appreciate your feedback and willingness to use our tools! Thanks!
